### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joenye** [joenye/creepy-js-client#1]
- [x] Separate out API logic
- [x] Support new actions logic when added to server
- [x] Use redux for state management
- [ ] Support stairs navigation
- [ ] When scrolling out of visibility of current position, make a "re-centre" button appear
- [ ] Show player position and trace SVG paths
- [ ] Tile cache
- [ ] Player sessions
- [ ] Cards
